version: '2'
services:
  redis:
      image: redis
      ports:
        - "6379:6379"
  zookeeper:
      image: jplock/zookeeper
      ports:
        - "2181:2181"
        - "2888:2888"
        - "3888:3888"